Feature selection, Feature conversion, feature creation, feature engineering

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('credit.csv')

In [3]:
string_cols = ['credit_history', 'purpose', 'own_telephone',
       'personal_status', 'other_parties', 
       'other_payment_plans', 'housing', 'job','foreign_worker']

num_cols = [x for x in list(data.columns) if x not in string_cols]

In [4]:
credit = data[num_cols].copy()

In [5]:
credit.columns

Index(['checking_status', 'duration', 'credit_amount', 'savings_status',
       'employment', 'installment_commitment', 'residence_since',
       'property_magnitude', 'age', 'existing_credits', 'num_dependents',
       'class'],
      dtype='object')

In [6]:
# changing appropriate categorical columns to numerical 
rep = {
    'checking_status':{'\'no checking\'':0, '\'>=200\'':2, '\'0<=X<200\'':1  ,'\'<0\'':-1},
    'savings_status':{'\'no known savings\'':0, '\'<100\'':50 ,'\'100<=X<500\'':350, '\'500<=X<1000\'':750, '\'>=1000\'':1500},
    'employment':{'unemployed':0, '\'<1\'':0.5, '\'1<=X<4\'':2.5, '\'4<=X<7\'':5.5, '\'>=7\'':8.5},
    'property_magnitude': {'\'real estate\'':3,'car':2,'\'life insurance\'':1,'\'no known property\'':0}
}

credit.replace(rep, inplace=True)

In [7]:
# Converting BAD to 1 GOOD to 0
credit.replace({'class':{'good':0, 'bad':1}}, inplace=True)

In [8]:
# Create a no checking status column
credit['no_checking'] = credit['checking_status'].apply(lambda x: 1 if x==0 else 0)

In [9]:
# Create an average 'installment_commitment' by personal_status feature
credit['commit_by_p_status'] = data[['personal_status', 'installment_commitment']].groupby(
    'personal_status').transform(np.mean)

In [10]:
credit

,checking_status,duration,credit_amount,savings_status,employment,installment_commitment,residence_since,property_magnitude,age,existing_credits,num_dependents,class,no_checking,commit_by_p_status
0,-1,6,1169,0,8.5,4,4,3,67,2,1,0,0,3.093066
1,1,48,5951,50,2.5,2,2,3,22,1,1,1,0,2.829032
2,0,12,2096,50,5.5,2,3,3,49,1,2,0,1,3.093066
3,-1,42,7882,50,5.5,2,4,1,45,1,2,0,0,3.093066
4,-1,24,4870,50,2.5,3,4,0,53,2,2,1,0,3.093066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,12,1736,50,5.5,3,4,3,31,1,1,0,1,2.829032
996,-1,30,3857,50,2.5,4,4,1,40,1,1,0,0,2.500000
997,0,12,804,50,8.5,4,4,2,38,1,1,0,1,3.093066
998,-1,45,1845,50,2.5,4,4,0,23,1,1,1,0,3.093066
999,1,45,4576,350,0.0,3,4,2,27,1,1,0,0,3.093066

In [12]:
numeric = credit
numeric.to_csv('data/data_numeric.csv', index=False)